server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/cards?createDatabaseIfNotExist=true

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
  profiles:
    active:  "prod"
  application:
    name: "cards"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
     web:
       exposure:
         include: "*"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE


