server:
  port: 8071

spring:
  application:
    name: "configserver"

  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Yoki45/spring-cloud-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

            #native:
           # search-locations: "config"
encrypt:
  key: "72E2EFA0AA79B3791B5E2637F4B26F45"

