server:
  port: 8071

spring:
  application:
    name: "configserver"

  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Yoki45/spring-cloud-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"

            #native:
           # search-locations: "config"
encrypt:
  key: "72E2EFA0AA79B3791B5E2637F4B26F45"


  management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
      endpoint:
        health:
          probes:
            enabled: true



