package com.microservices.accounts.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(name = "Accounts",description = "Holds accounts information of a customer")
public class AccountsDto {

    @Schema(description = "Autogenerated account number")
    private Long accountNumber;
    @Schema(description = "Customer's account type", example = "Savings")
    private String accountType;
    @Schema(description = "Customer's Branch name", example = "TRM Bank")
    private String branchName;
    @Schema(description = "Customer's home address")
    private String branchAddress;
}
